//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnThiWeb1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }

        public int Id { get; set; }
        [RegularExpression(@"[0-9]*", ErrorMessage = "Must be a number")]
        [Range(100, Double.PositiveInfinity)]
      /*  [Range(100,maximum:1000)]
        [RegularExpression("([1-9][0-9]*)")]*/
        public string Fullname { get; set; }


        [Required(ErrorMessage = "Địa chỉ email là bắt buộc")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Email sai cú pháp")]
        public string Email { get; set; }
        [RegularExpression("[A-Z]{2}[0-9]{4}")]
         public string Password { get; set; }
        [Compare("Password")]
        public string RePassword { get; set; }
       /* [Required(ErrorMessage = "Địa chỉ email là bắt buộc")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Email sai cú pháp")]*/
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
